name: relperm
channels:
  - numba
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0=py310haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - asteval=0.9.27=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py310haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=ha925a31_2
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.9.24=py310haa95532_0
  - cffi=1.15.1=py310h2bbff1b_0
  - colorama=0.4.5=py310haa95532_0
  - console_shortcut=0.1.1=4
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - emcee=3.1.3=pyhd8ed1ab_0
  - entrypoints=0.4=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fftw=3.3.10=nompi_h52fa85e_103
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - future=0.18.2=pyhd8ed1ab_6
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=vc14hc45fdbb_0
  - idna=3.4=py310haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.15.2=py310haa95532_0
  - ipython=8.6.0=py310haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py310haa95532_1
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_0
  - jsonschema=4.16.0=py310haa95532_0
  - jupyter_client=7.3.5=py310haa95532_0
  - jupyter_core=4.11.2=py310haa95532_0
  - jupyter_server=1.18.1=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.4.2=py310hd77b12b_0
  - libffi=3.4.2=hd77b12b_4
  - libiconv=1.16=h2bbff1b_2
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.2.0=he0120a3_1
  - libwebp=1.2.2=h2bbff1b_0
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - llvmlite=0.39.1=py310_0
  - lmfit=1.0.3=pyhd8ed1ab_0
  - lxml=4.9.1=py310h1985fb9_0
  - lz4-c=1.9.3=h2bbff1b_1
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib=3.5.1=py310haa95532_1
  - matplotlib-base=3.5.1=py310hd77b12b_1
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mistune=0.8.4=py310h2bbff1b_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - munkres=1.1.4=py_0
  - nbclassic=0.4.8=py310haa95532_0
  - nbclient=0.5.13=py310haa95532_0
  - nbconvert=6.5.4=py310haa95532_0
  - nbformat=5.5.0=py310haa95532_0
  - nest-asyncio=1.5.5=py310haa95532_0
  - notebook=6.5.2=py310haa95532_0
  - notebook-shim=0.2.2=py310haa95532_0
  - numba=0.56.4=np1.21py3.10hd3205ba_g288a38bbd_0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpy=1.23.4=py310h60c9a35_0
  - numpy-base=1.23.4=py310h04254f7_0
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.5.1=py310h4ed8f06_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py310hdc2b20a_0
  - pip=22.2.2=py310haa95532_0
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyerfa=2.0.0=py310h2bbff1b_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.9.2=py310hd77b12b_6
  - pyrsistent=0.18.0=py310h2bbff1b_0
  - python=3.10.8=hbb2ffb3_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - pytz=2022.1=py310haa95532_0
  - pywin32=302=py310h2bbff1b_2
  - pywinpty=2.0.2=py310h5da7b33_0
  - pyyaml=6.0=py310h2bbff1b_0
  - pyzmq=23.2.0=py310hd77b12b_0
  - qt=5.9.7=vc14h73c81de_0
  - scipy=1.9.3=py310h86744a3_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.5.0=py310haa95532_0
  - setuptools-scm=7.0.5=pyhd8ed1ab_1
  - sip=4.19.13=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py310haa95532_1
  - soupsieve=2.3.2.post1=py310haa95532_0
  - sqlite=3.39.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.13.1=py310haa95532_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py310h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022f=h04d1e81_0
  - uncertainties=3.1.7=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=0.58.0=py310haa95532_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - winpty=0.4.3=4
  - xz=5.2.6=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
