name: relperm
channels:
  - conda-forge
dependencies:
  - asteval=1.0.2=pyhd8ed1ab_0
  - brotli=1.1.0=hcfcfb64_1
  - brotli-bin=1.1.0=hcfcfb64_1
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2024.7.4=h56e8100_0
  - cairo=1.18.0=h32b962e_3
  - certifi=2024.7.4=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h0d7def4_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - double-conversion=3.3.0=h63175ca_0
  - emcee=3.1.6=pyhd8ed1ab_0
  - expat=2.6.2=h63175ca_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py312h4389bb4_0
  - freetype=2.12.1=hdaf720e_2
  - future=1.0.0=pyhd8ed1ab_0
  - graphite2=1.3.13=h63175ca_1003
  - harfbuzz=9.0.0=h2bedf89_1
  - icu=75.1=he0c23c2_0
  - intel-openmp=2024.2.0=h57928b3_980
  - kiwisolver=1.4.5=py312h0d7def4_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=23_win64_mkl
  - libbrotlicommon=1.1.0=hcfcfb64_1
  - libbrotlidec=1.1.0=hcfcfb64_1
  - libbrotlienc=1.1.0=hcfcfb64_1
  - libcblas=3.9.0=23_win64_mkl
  - libclang13=18.1.8=default_ha5278ca_1
  - libdeflate=1.21=h2466b09_0
  - libexpat=2.6.2=h63175ca_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.80.3=h7025463_1
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_2
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=23_win64_mkl
  - libpng=1.6.43=h19919ed_0
  - libsqlite=3.46.0=h2466b09_0
  - libtiff=4.6.0=hb151862_4
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=hcd874cb_0
  - libxml2=2.12.7=h0f24e4e_4
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_1
  - llvmlite=0.43.0=py312h1f7db74_0
  - lmfit=1.3.2=pyhd8ed1ab_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.9.1=py312h2e8e312_2
  - matplotlib-base=3.9.1=py312h90004f6_2
  - mkl=2024.1.0=h66d3029_694
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - numba=0.60.0=py312hcccf92d_0
  - numpy=2.0.1=py312h49bc9c5_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.3.1=h2466b09_2
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h72972c8_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=h3d7b363_0
  - pillow=10.4.0=py312h381445a_0
  - pip=24.2=pyhd8ed1ab_0
  - pixman=0.43.4=h63175ca_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyside6=6.7.2=py312h2ee7485_2
  - python=3.12.4=h889d299_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.7.2=hbb46ec1_4
  - scipy=1.14.0=py312h1f4e10d_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=72.1.0=pyhd8ed1ab_0
  - setuptools-scm=8.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.14.2=py312h1a27103_0
  - tbb=2021.12.0=hc790b64_3
  - tk=8.6.13=h5226925_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4.1=py312h4389bb4_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - uncertainties=3.2.2=pyhd8ed1ab_1
  - vc=14.3=h8a93ad2_20
  - vc14_runtime=14.40.33810=ha82c5b3_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zlib=1.3.1=h2466b09_1
  - zstd=1.5.6=h0ea2cb4_0
prefix: C:\ProgramData\miniforge3\envs\relperm